### ISSUE TITLE
Issue accessing authorization system during Orchestration request

### ISSUE THREAD

**Issue by sumi0910** [arrowhead-f/sos-examples-spring#12]
Hello,

I am trying to run demo-car example in "insecure" mode. changed the ssl-enable flag to false in application.properties. Unable to understand from where the request to the link http://0.0.0.0:8445/authorization/intracloud/check is arising. Tried looking at the code and request also but couldn't find any info as it is already set to null.Let me know what can be issue and how can I make it working.
![image](https://user-images.githubusercontent.com/44111991/70043698-37f69600-15c1-11ea-9537-01afccd3ef17.png)
Thanks and regards,
Suman

**Comment by borditamas** [comment]
Hello,

it's happening because the demo system is  out of your docker network. This issue have been solved nowadays, so what you need to do is to update your docker containers to the latest one and set the domain.name and domain.port in the config files. The domain name and port should be the same as you reach for example the swaggers of the core systems on.
